### ISSUE TITLE
ogurictl seems to be missing

### ISSUE THREAD

**Issue by MrYakobo** [vilhalmer/oguri#18] opened 2019-11-18 19:33 UTC
Hello, very promising project indeed. I have a problem with one thing though.

```
$ oguri -h
Usage: oguri [-c <config-path>]

  -c  Path to the configuration file to use.
      (default: $XDG_CONFIG_HOME/oguri/config)
  -h  Show this text.

To control oguri while it is running, use `ogurictl`.
```

> To control oguri while it is running, use `ogurictl`.

[The promised utility is nowhere to be seen :scream: ](https://github.com/vilhalmer/oguri/search?q=ogurictl&unscoped_q=ogurictl)

**Comment by vilhalmer** [comment] 2019-11-18 20:06
Indeed, that's because it doesn't exist yet. ;) Hilarious timing though, because I finally started writing it this morning. Finishing it is one of the two remaining issues for the 1.0 milestone: https://github.com/vilhalmer/oguri/milestone/1

Duplicate of #3.

**Closed by vilhalmer** 2019-11-18 20:06 UTC
